/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module "vue-router/auto-routes" {
    import type {
        RouteRecordInfo,
        ParamValue,
        ParamValueOneOrMore,
        ParamValueZeroOrMore,
        ParamValueZeroOrOne,
    } from "vue-router";

    /**
     * Route name map generated by unplugin-vue-router
     */
    export interface RouteNamedMap {
        "/": RouteRecordInfo<
            "/",
            "/",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/admin/": RouteRecordInfo<
            "/admin/",
            "/admin",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/ai-butler/": RouteRecordInfo<
            "/ai-butler/",
            "/ai-butler",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/community/": RouteRecordInfo<
            "/community/",
            "/community",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/consultation/": RouteRecordInfo<
            "/consultation/",
            "/consultation",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/customer/": RouteRecordInfo<
            "/customer/",
            "/customer",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/customer/login": RouteRecordInfo<
            "/customer/login",
            "/customer/login",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/login/": RouteRecordInfo<
            "/login/",
            "/login",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/settings/": RouteRecordInfo<
            "/settings/",
            "/settings",
            Record<never, never>,
            Record<never, never>,
            never
        >;
        "/shop/": RouteRecordInfo<
            "/shop/",
            "/shop",
            Record<never, never>,
            Record<never, never>,
            never
        >;
    }

    /**
     * Route file to route info map by unplugin-vue-router.
     * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
     *
     * Each key is a file path relative to the project root with 2 properties:
     * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
     * - views: names of nested views (can be passed to <RouterView name="...">)
     *
     * @internal
     */
    export interface _RouteFileInfoMap {
        "src/pages/index.vue": {
            routes: "/";
            views: never;
        };
        "src/pages/admin/index.vue": {
            routes: "/admin/";
            views: never;
        };
        "src/pages/ai-butler/index.vue": {
            routes: "/ai-butler/";
            views: never;
        };
        "src/pages/community/index.vue": {
            routes: "/community/";
            views: never;
        };
        "src/pages/consultation/index.vue": {
            routes: "/consultation/";
            views: never;
        };
        "src/pages/customer/index.vue": {
            routes: "/customer/";
            views: never;
        };
        "src/pages/customer/login.vue": {
            routes: "/customer/login";
            views: never;
        };
        "src/pages/login/index.vue": {
            routes: "/login/";
            views: never;
        };
        "src/pages/settings/index.vue": {
            routes: "/settings/";
            views: never;
        };
        "src/pages/shop/index.vue": {
            routes: "/shop/";
            views: never;
        };
    }

    /**
     * Get a union of possible route names in a certain route component file.
     * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
     *
     * @internal
     */
    export type _RouteNamesForFilePath<FilePath extends string> =
        _RouteFileInfoMap extends Record<FilePath, infer Info>
            ? Info["routes"]
            : keyof RouteNamedMap;
}
